### ISSUE TITLE
ModuleNotFoundError: No module named 'click._bashcomplete'

### ISSUE THREAD

**Issue by Ribo-Py** [megagonlabs/ditto#22]
!CUDA_VISIBLE_DEVICES=0 python train_ditto.py \
  --task Structured/DBLP-ACM \
  --batch_size 32 \
  --max_len 128 \
  --lr 3e-5 \
  --n_epochs 20 \
  --finetuning \
  --lm roberta \
  --fp16 \
  --da drop_col

Traceback (most recent call last):
  File "train_ditto.py", line 13, in <module>
    from ditto_light.knowledge import *
  File "/home/ec2-user/SageMaker/vendor_matching/ditto/ditto_light/knowledge.py", line 5, in <module>
    import spacy
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/typer/__init__.py", line 31, in <module>
    from .main import Typer, run
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'

**Comment by Ribo-Py** [comment]
updated spacy resolved the issue.
